config/routes.rb
Rails.application.routes.draw do  
  resources :supplies
  resources :distributors
  resources :books
  resources :cashiers
  resources :sales, only: [:create, :index, :new]

  get    '/home',     to: 'dashboards#home'
  get    '/contact',  to: 'dashboards#contact'
  get    '/help',     to: 'dashboards#help'
  get    '/about',    to: 'dashboards#about'
  get    '/signup',   to: 'cashiers#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  
  root "sessions#new"
end

app/models/distributor.rb
class Distributor < ApplicationRecord
	include Visible

	has_many :supplies, dependent: :destroy
	has_many :books, through: :supplies

	validates :distributor_name, presence: true 
	validates :address, presence: true 
	validates :telephone, presence: true, numericality: { only_integer: true }
end

app/controllers/distributors_controller.rb
class DistributorsController < ApplicationController
  before_action :set_distributor, only: %i[ show edit update destroy ]
  before_action :is_login

  # GET /distributors or /distributors.json
  def index
     @distributors = Distributor.all.recent
  end

  # GET /distributors/1 or /distributors/1.json
  def show
  end

  # GET /distributors/new
  def new
    @distributor = Distributor.new
  end

  # GET /distributors/1/edit
  def edit
  end

  # POST /distributors or /distributors.json
  def create
    @distributor = Distributor.new(distributor_params)

    respond_to do |format|
      if @distributor.save
        format.html { redirect_to distributors_url, notice: "Distributor was successfully created." }
        format.json { render :index, status: :created, location: @distributor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @distributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distributors/1 or /distributors/1.json
  def update
    respond_to do |format|
      if @distributor.update(distributor_params)
        format.html { redirect_to distributors_url, notice: "Distributor was successfully updated." }
        format.json { render :index, status: :ok, location: @distributor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @distributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distributors/1 or /distributors/1.json
  def destroy
    @distributor.destroy

    respond_to do |format|
      format.html { redirect_to distributors_url, notice: "Distributor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distributor
      @distributor = Distributor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def distributor_params
      params.require(:distributor).permit(:distributor_name, :address, :telephone)
    end

    def is_login
      unless logged_in?
        redirect_to root_path, notice: "Please Login!"
      end
    end
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/views/distributors/_distributor.html.erb
<div id="<%= dom_id distributor %>">
  <p>
    <strong>Distributor name:</strong>
    <%= distributor.distributor_name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= distributor.address %>
  </p>

  <p>
    <strong>Telephone:</strong>
    <%= distributor.telephone %>
  </p>

</div>

app/views/distributors/_form.html.erb
<%= form_with(model: distributor) do |form| %>
  <% if distributor.errors.any? %>
    <div style="color: red" class="alert alert-danger">
      <h2><%= pluralize(distributor.errors.count, "error") %> prohibited this distributor from being saved:</h2>

      <ul>
        <% distributor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :distributor_name, style: "display: block", class: "form-label" %>
    <%= form.text_field :distributor_name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :address, style: "display: block", class: "form-label" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :telephone, style: "display: block", class: "form-label" %>
    <%= form.number_field :telephone, class: "form-control" %>
  </div>

  <div class="d-grid gap-1 mb-3">
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/distributors/_sidebar.html.erb
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3" data-turbo="false">
        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to root_url, class: "nav-link", id: "HomeLabel" do %>
              <span data-feather="home"></span>
              Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path, class: "nav-link" do %>
              <span data-feather="book-open"></span>
              Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to distributors_path, class: "nav-link active" do %>
              <span data-feather="truck"></span>
              Distributors
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to current_cashier, class: "nav-link" do %>
              <span data-feather="users"></span>
              Cashiers
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to supplies_path, class: "nav-link" do %>
              <span data-feather="package"></span>
              Supply
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to sales_path, class: "nav-link" do %>
              <span data-feather="shopping-bag"></span>
              Sales
            <% end %>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

app/views/distributors/edit.html.erb
<% provide(:title, "Edit #{@distributor.distributor_name}") %>

<%= render 'distributors/sidebar' %>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" data-turbo="false">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Editing <%= @distributor.distributor_name %></h1>
        <%= link_to "<<< Back to Distributors", distributors_path, class: "btn btn-outline-primary" %>
      </div>

      <%= render "form", distributor: @distributor %>

    </main>
  </div>
</div>

app/views/distributors/index.html.erb
<% provide(:title, 'Distributors') %>

<%= render 'distributors/sidebar' %>

<% no = 0 %>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" data-turbo="false">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Distributors</h1>
        <%= link_to "New distributor", new_distributor_path, class: "btn btn-outline-primary" %>
      </div>

      <% if notice %>
        <div class="mx-auto alert alert-success text-center">
          <%= notice %>
        </div>
      <% end %>

      <% unless @distributors.empty? %>
      
      <div class="d-flex flex-wrap align-items-start justify-content-start justify-content-lg-start">

        <table class="table table-stripped table-hover table-align-middle table-primary">
          <thead> 
            <tr class="text-center">
              <th scope="col">#</th>
              <th scope="col">Distributor Name</th>
              <th scope="col">Address</th>
              <th scope="col">Telephone</th>
              <th scope="col">Miscellaneous</th>
            </tr>
          </thead>

          <% @distributors.each do |distributor| %>

          <tbody>
            <tr>
              <th scope="col" class="text-center"><%= no += 1 %></th>
              <td class="text-center"><%= distributor.distributor_name %></td>
              <td class="text-center"><%= distributor.address %></td>
              <td class="text-center"><%= distributor.telephone %></td>
              <td class="text-center">
                <button id="dropdownAction2" type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                  Edit/delete Distributor
                </button>
                <ul class="dropdown-menu" aria-labelledy="dropdownAction2">
                  <li>
                    <%= link_to "Edit this distributor", edit_distributor_path(distributor), class: "dropdown-item link-primary" %>
                  </li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li>
                    <%= button_to "Destroy this distributor", distributor, method: :delete, class: "dropdown-item link-danger" %>
                  </li>
                </ul>
              </td>
            </tr>
          </tbody>

          <% end %>

        </table>
      </div>

      <% else %>
        <h1 class="text-center">
          No Data.
        </h1>
      <% end %>
    </main>
  </div>
</div>

app/views/distributors/new.html.erb
<% provide(:title, 'New Distributor') %>

<%= render 'distributors/sidebar' %>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" data-turbo="false">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">New Distributor</h1>
      </div>

      <%= render "form", distributor: @distributor %>

    </main>
  </div>
</div>

app/views/distributors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @distributor %>

<div>
  <%= link_to "Edit this distributor", edit_distributor_path(@distributor) %> |
  <%= link_to "Back to distributors", distributors_path %>

  <%= button_to "Destroy this distributor", @distributor, method: :delete %>
</div>