config/routes.rb
Rails.application.routes.draw do  
  resources :supplies
  resources :distributors
  resources :books
  resources :cashiers
  resources :sales, only: [:create, :index, :new]

  get    '/home',     to: 'dashboards#home'
  get    '/contact',  to: 'dashboards#contact'
  get    '/help',     to: 'dashboards#help'
  get    '/about',    to: 'dashboards#about'
  get    '/signup',   to: 'cashiers#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  
  root "sessions#new"
end

app/models/book.rb
class Book < ApplicationRecord
  include Visible

  has_many :supplies, dependent: :destroy
  has_many :distributors, through: :supplies
  has_many :sales
  has_one_attached :cover

  validates :title, presence: true 
  validates :noisbn, presence: true, numericality: { only_integer: true }
  validates :writer, presence: true
  validates :description, presence: true 
  validates :publisher, presence: true 
  validates :year, presence: true, numericality: { only_integer: true }
  validates :stock, presence: true, numericality: { only_integer: true }
  validates :price, presence: true, numericality: { only_integer: true }
  validates :selling_price, presence: true, numericality: { only_integer: true }
  validates :ppn, presence: true, numericality: { only_float: true }
  validates :discount, numericality: { only_float: true }
  validates :cover, content_type: { in: %w[image/jpeg image/png image/gif], message: "Must be a valid image format" }, size: { less_than: 5.megabytes, message: "Should be less than 5MB" }

  def display_cover
    cover.variant resize_to_limit: [300, 300]
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :is_login

  # GET /books or /books.json
  def index
    @books = Book.all.recent
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.cover.attach(params[:book][:cover])

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
     end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :cover, :noisbn, :writer, :description, :publisher, :year, :stock, :price, :selling_price, :ppn, :discount)
    end

    def is_login
      unless logged_in?
        redirect_to root_path, notice: "Please Login"
      end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Cover:</strong>
    <%= link_to book.cover.filename, book.cover if book.cover.attached? %>
  </p>

  <p>
    <strong>Noisbn:</strong>
    <%= book.noisbn %>
  </p>

  <p>
    <strong>Writer:</strong>
    <%= book.writer %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= book.publisher %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= book.year %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= book.stock %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= book.price %>
  </p>

  <p>
    <strong>Selling price:</strong>
    <%= book.selling_price %>
  </p>

  <p>
    <strong>PPN:</strong>
    <%= book.ppn %>
  </p>

  <p>
    <strong>Discount:</strong>
    <%= book.discount %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red" class="alert alert-danger">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, style: "display: block", class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :cover, style: "display: block", class: "form-label" %>
    <%= form.file_field :cover, accept: "image/jpeg,image/png,image/gif", class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :noisbn, style: "display: block", class: "form-label" %>
    <%= form.number_field :noisbn, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :writer, style: "display: block", class: "form-label" %>
    <%= form.text_field :writer, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, style: "display: block", class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :publisher, style: "display: block", class: "form-label" %>
    <%= form.text_field :publisher, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :year, style: "display: block", class: "form-label" %>
    <%= form.select :year, (Date.today.year - 20)..(Date.today.year + 10),{} , { class: "form-select" }  %>
  </div>

  <div class="mb-3">
    <%= form.label :stock, style: "display: block", class: "form-label" %>
    <%= form.number_field :stock, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :price, style: "display: block", class: "form-label" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :selling_price, style: "display: block", class: "form-label" %>
    <%= form.number_field :selling_price, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :ppn, style: "display: block", class: "form-label" %>
    <%= form.text_field :ppn, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :discount, style: "display: block", class: "form-label" %>
    <%= form.text_field :discount, class: "form-control" %>
  </div>

  <div class="mb-3 d-grid gap-1" data-turbo="false">
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/books/_sidebar.html.erb
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3" data-turbo="false">
        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to root_url, class: "nav-link", id: "HomeLabel" do %>
              <span data-feather="home"></span>
              Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path, class: "nav-link active" do %>
              <span data-feather="book-open"></span>
              Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to distributors_path, class: "nav-link" do %>
              <span data-feather="truck"></span>
              Distributors
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to current_cashier, class: "nav-link" do %>
              <span data-feather="users"></span>
              Cashiers
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to supplies_path, class: "nav-link" do %>
              <span data-feather="package"></span>
              Supply
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to sales_path, class: "nav-link" do %>
              <span data-feather="shopping-bag"></span>
              Sales
            <% end %>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

app/views/books/edit.html.erb
<% provide(:title, @book.title) %>

<%= render 'books/sidebar' %>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Editing book <%= @book.title %></h1>
      </div>
      <%= render "form", book: @book %>

      <br>

      <div class="border-top d-grid gap-1">
        <br>
        <br>
        <%= link_to "Show this book", @book, class: "btn btn-outline-primary" %>
        <%= link_to "Back to books", books_path, class: "btn btn-outline-danger" %>
      </div>
    </main>
  </div>
</div>

app/views/books/index.html.erb
<% provide(:title, 'Books') %>

<%= render 'books/sidebar' %>

<% no = 0 %>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" data-turbo="false">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Books</h1>
        <%= link_to "New book", new_book_path, class: "btn btn-outline-primary" %>
      </div>

      <% if notice %>
        <div class="mx-auto alert alert-success">
          <%= notice %>
        </div>
      <% end %>

      <% unless @books.empty? %>

      <div class="d-flex flex-wrap align-items-start justify-content-start justify-content-lg-start">

        <table class="table table-stripped table-hover table-align-middle table-primary">
          <thead>
            <tr class="text-center">
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Writer</th>
              <th scope="col">Publisher</th>
              <th scope="col">Year</th>
              <th scope="col">Stock</th>
              <th scope="col">Selling Price</th>
            </tr>
          </thead>

          <% @books.each do |book| %>

          <tbody>
            <tr>
              <th scope="col" class="text-center"><%= no += 1 %></th>
              <td>
                <%= image_tag book.cover, width: "30", class: "img-fluid" if book.cover.attached? %>
                <%= link_to book.title, book, class: "text-decoration-none" %>
              </td>
              <td class="text-center"><%= book.writer %></td>
              <td class="text-center"><%= book.publisher %></td>
              <td class="text-center"><%= book.year %></td>
              <td class="text-center"><%= book.stock %></td>
              <td class="text-center">Rp. <%= book.selling_price %></td>
            </tr>
          </tbody>

          <% end %>

        </table>
      </div>
      <% else %>
        <h1 class="text-center">
          No Data.
        </h1>
      <% end %>
    </main>
<%= render 'layouts/closing' %>

app/views/books/new.html.erb
<% provide(:title, 'New Book') %>

<%= render 'books/sidebar' %>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" data-turbo="false">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">New book</h1>
      </div>

      <%= render "form", book: @book %>

    </main>
  </div>
</div>

app/views/books/show.html.erb
<% provide(:title, @book.title) %>
<%= render 'books/sidebar' %>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" data-turbo="false">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2"><%= @book.title %></h1> 
        <div class="btn-toolbar mb-2 mb-mb-0">
            <div class="btn-group me-2">
                <button id="dropdownAction1" type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    Edit/Delete Book
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownAction1">
                    <li>
                        <%= link_to "Edit this book", edit_book_path(@book), class: "dropdown-item link-primary" %>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <%= button_to "Destroy this book", @book, method: :delete, class: "dropdown-item link-danger" %>
                    </li>
                </ul>
            </div>
        </div>
      </div>
      <div class="d-flex flex-wrap align-items-start justify-content-start justify-content-lg-start">
        <div class="me-auto p-2">
            <% flash.each do %>
                <p class="alert alert-success">
                    <%= notice %>
                </p>
            <% end %>
            <center>
                <h1>Synopsis</h1>
            </center>
            <%= @book.description %>
            <br>
            <br>

            <div class="d-flex bd-highlight">
                <table class="table table-hover table-stripped table-sm table-align-middle w-auto p-2 flex-fill bd-highlight">
                    <tr>
                        <th scope="col">Title</th>
                        <td><%= @book.title %></td>
                    </tr>
                    <tr>
                        <th scope="col">NOISBN</th>
                        <td><%= @book.noisbn %></td>
                    </tr>
                    <tr>
                        <th scope="col">Writer</th>
                        <td><%= @book.writer %></td>
                    </tr>
                    <tr>
                        <th scope="col">Publisher</th>
                        <td><%= @book.publisher %></td>
                    </tr>
                    <tr>
                        <th scope="col">Year</th>
                        <td><%= @book.year %></td>
                    </tr>
                    <tr>
                        <th scope="col">Stock</th>
                        <td><%= @book.stock %></td>
                    </tr>
                    <tr>
                        <th scope="col">Price</th>
                        <td>Rp. <%= @book.price %></td>
                    </tr>
                    <tr>
                        <th scope="col">Selling Price</th>
                        <td>Rp. <%= @book.selling_price %></td>
                    </tr>
                    <tr>
                        <th scope="col">PPN</th>
                        <td><%= @book.ppn %></td>
                    </tr>
                    <tr>
                        <th scope="col">Discount</th>
                        <td><%= @book.discount %></td>
                    </tr>
            </table>
            <%= image_tag @book.cover, width: "300", class: "img-fluid col-md-4 ms-auto" if @book.cover.attached? %>
            </div>
        </div>
    </div>
</main>
  </div>
</div>