config/routes.rb
Rails.application.routes.draw do  
  resources :supplies
  resources :distributors
  resources :books
  resources :cashiers
  resources :sales, only: [:create, :index, :new]

  get    '/home',     to: 'dashboards#home'
  get    '/contact',  to: 'dashboards#contact'
  get    '/help',     to: 'dashboards#help'
  get    '/about',    to: 'dashboards#about'
  get    '/signup',   to: 'cashiers#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  
  root "sessions#new"
end

app/models/supply.rb
class Supply < ApplicationRecord
  include Visible

  belongs_to :book
  belongs_to :distributor

  validates :amount, presence: true, numericality: { only_integer: true }

  after_save :increaseBook

  private 
    def increaseBook
      bookID = self.book_id
      bookStock = Book.find(bookID).stock
      total = Supply.find(self.id).amount

      Book.find(bookID).update(stock: bookStock + total)
    end
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action :set_supply, only: %i[ show edit update destroy ]
  before_action :is_login

  # GET /supplies or /supplies.json
  def index
    @supplies = Supply.all.recent
  end

  # GET /supplies/1 or /supplies/1.json
  def show
  end

  # GET /supplies/new
  def new
    @supply = Supply.new
  end

  # GET /supplies/1/edit
  def edit
  end

  def search
    @search = Book.find(params[:noisbn])
  end

  # POST /supplies or /supplies.json
  def create
    @supply = Supply.new(supply_params)

    respond_to do |format|
      if @supply.save
        format.html { redirect_to supplies_path, notice: "Supply was successfully created." }
        format.json { render :show, status: :created, location: @supply }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1 or /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to supply_url(@supply), notice: "Supply was successfully updated." }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1 or /supplies/1.json
  def destroy
    @supply.destroy

    respond_to do |format|
      format.html { redirect_to supplies_url, notice: "Supply was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supply_params
      params.require(:supply).permit(:book_id, :distributor_id, :amount, :date)
    end

    def is_login
      unless logged_in?
        redirect_to root_path, notice: "Please Login!"
      end
    end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.erb
<%= form_with(model: supply) do |form| %>
  <% if supply.errors.any? %>
    <div style="color: red" class="col-md-6 mx-auto alert alert-danger text-center">
      <h2><%= pluralize(supply.errors.count, "error") %> prohibited this supply from being saved:</h2>

      <ul>
        <% supply.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :book_id, style: "display: block", class: "form-label" %>
    <%= form.collection_select(:book_id, Book.all, :id, :title, {}, {class: "form-control"} ) %>
  </div>

  <div class="mb-3">
    <%= form.label :distributor_id, style: "display: block", class: "form-label" %>
    <%= form.collection_select(:distributor_id, Distributor.all, :id, :distributor_name, {},  {class: "form-control"} ) %>
  </div>

  <div class="mb-3">
    <%= form.label :amount, style: "display: block", class: "form-label" %>
    <%= form.number_field :amount, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :date, style: "display: block", class: "form-label" %>
    <%= form.date_field :date, class: "form-control" %>
  </div>

  <div class="mb-3 d-grid gap-1">
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/supplies/_sidebar.html.erb
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3" data-turbo="false">
        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to root_url, class: "nav-link", id: "HomeLabel" do %>
              <span data-feather="home"></span>
              Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path, class: "nav-link" do %>
              <span data-feather="book-open"></span>
              Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to distributors_path, class: "nav-link" do %>
              <span data-feather="truck"></span>
              Distributors
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to current_cashier, class: "nav-link" do %>
              <span data-feather="users"></span>
              Cashiers
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to supplies_path, class: "nav-link active" do %>
              <span data-feather="package"></span>
              Supply
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to sales_path, class: "nav-link" do %>
              <span data-feather="shopping-bag"></span>
              Sales
            <% end %>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

app/views/supplies/_supply.html.erb
<div id="<%= dom_id supply %>">
  <p>
    <strong>Book:</strong>
    <%= supply.book_id %>
  </p>

  <p>
    <strong>Distributor:</strong>
    <%= supply.distributor_id %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= supply.amount %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= supply.date %>
  </p>

</div>

app/views/supplies/edit.html.erb
<% provide(:title, 'Edit Supply') %>

<%= render 'supplies/sidebar' %>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 ">
    <h1 class="h2">Editing supply</h1>
    <%= link_to "Back to supplies", supplies_path, class: "btn btn-outline-primary" %>
  </div>

  <%= render "form", supply: @supply %>

  <br>

  <div>
    <%= link_to "Show this supply", @supply, class: "btn-outline-primary" %> 
  </div>
</main>

app/views/supplies/index.html.erb
<% provide(:title, 'Supplies') %>

<%= render 'supplies/sidebar' %>

<% no = 0 %>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" data-turbo="false">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Supplies</h1>
    <%= link_to "New supply", new_supply_path, class: "btn btn-outline-primary" %>
  </div>

  <% if notice %>
    <div class="mx-auto alert alert-success text-center">
      <%= notice %>
    </div>
  <% end %>

  <% unless @supplies.empty? %>

  <div class="d-flex flex-wrap align-items-start justify-content-start justify-content-lg-start">
    <table class="table table-stripped table-hover table-align-middle table-primary">
      <thead>
        <tr class="text-center">
          <th scope="col">#</th>
          <th scope="col">Book Title</th>
          <th scope="col">Distributor</th>
          <th scope="col">Amount</th>
          <th scope="col">Date input</th>
        </tr>
      </thead>
      <% @supplies.each do |supply| %>
        <tbody>
          <tr>
            <th scope="col" class="text-center"><%= no += 1 %></th>
            <td>
              <%= image_tag supply.book.cover, width: "30", class: "img-fluid" if supply.book.cover.attached? %>
              <%= supply.book.title %>
            </td>
            <td class="text-center">
              <%= supply.distributor.distributor_name %>
            </td>
            <td class="text-center">
              <%= supply.amount %>
            </td>
            <td class="text-center">
              <%= supply.date&.strftime('%d %B %Y') %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>

  <% else %>
    <h1 class="text-center">
      No Data.
    </h1>
  <% end %>
  
</main>
 
<%= render 'layouts/closing' %>

app/views/supplies/new.html.erb
<% provide(:title, 'New Supply') %>

<%= render 'supplies/sidebar' %>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">New supply</h1>
  </div>
  <%= render "form", supply: @supply %>
</main>
<%= render 'layouts/closing' %>

app/views/supplies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @supply %>

<div>
  <%= link_to "Edit this supply", edit_supply_path(@supply) %> |
  <%= link_to "Back to supplies", supplies_path %>

  <%= button_to "Destroy this supply", @supply, method: :delete %>
</div>