config/routes.rb
Rails.application.routes.draw do  
  resources :supplies
  resources :distributors
  resources :books
  resources :cashiers
  resources :sales, only: [:create, :index, :new]

  get    '/home',     to: 'dashboards#home'
  get    '/contact',  to: 'dashboards#contact'
  get    '/help',     to: 'dashboards#help'
  get    '/about',    to: 'dashboards#about'
  get    '/signup',   to: 'cashiers#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  
  root "sessions#new"
end

app/models/sale.rb
class Sale < ApplicationRecord
  include Visible

  belongs_to :book
  belongs_to :cashier

  validates :quantity, presence: true, numericality: { only_integer: true }
  validates :total, presence: true, numericality: { only_integer: true }
  validates :date, presence: true

  after_save :decreaseStock

  private 
    def decreaseStock
      bookID = self.book_id
      bookStock = Book.find(bookID).stock
      saleQuantity = Sale.find(id).quantity
      saleTotal = Sale.find(id).total

      Book.find(bookID).update(stock: bookStock - saleQuantity)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	before_action :is_login

	def index
		@sales = Sale.all.recent
	end

	def new
		@sale = Sale.new
	end

	def create
		@sale = Sale.new(sales_params)
		if @sale.save
			redirect_to sales_path, notice: "Purchasing Success!"
		else
			flash[:notice] = "There's an error. Try again"
			render :new, status: :unprocessable_entity
		end
	end

	private

		def sales_params
			params.require(:sale).permit(:book_id, :cashier_id, :quantity, :total, :date)
		end

		def is_login
			unless logged_in?
				redirect_to root_path, notice: "Please Login!"
			end
		end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale) do |f| %>
	<% if sale.errors.any? %>
		<div class="mx-auto alert alert-danger text-center">
			<h2>
				<%= pluralize(sale.errors.count, "error") %>
				Prohibuted this sales from being processed:
			</h2>

			<ul>
				<% sale.errors.each do |e| %>
					<li>
						<%= error.full_message %>
					</li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="mb-3">
		<%= f.label :book_id, class: "form-label" %>
		<%= f.collection_select(:book_id, Book.all, :id, :title, {}, { class: "form-select" } ) %>
	</div>
<!-- 	<div class="mb-3">

	</div> -->
	<div class="mb-3">
		<%= f.hidden_field :cashier_id, class: "form-control", value: @current_cashier.id %>
	</div>
	<div class="mb-3">
		<%= f.label :quantity, class: "form-label" %>
		<%= f.number_field :quantity, class: "form-control", value: 0 %>
	</div>
	<div class="mb-3">
		<%= f.label :total, class: "form-label" %>
		<%= f.number_field :total, class: "form-control" %>
	</div>
	<div class="mb-3">
		<%= f.hidden_field :date, class: "form-control", value: DateTime.now %>
	</div>
	<div class="mb-3 d-grid gap-1">
		<%= f.submit class: "btn btn-outline-primary" %>
	</div>
<% end %>

app/views/sales/_sidebar.html.erb
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3" data-turbo="false">
        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to root_url, class: "nav-link", id: "HomeLabel" do %>
              <span data-feather="home"></span>
              Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path, class: "nav-link" do %>
              <span data-feather="book-open"></span>
              Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to distributors_path, class: "nav-link" do %>
              <span data-feather="truck"></span>
              Distributors
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to current_cashier, class: "nav-link" do %>
              <span data-feather="users"></span>
              Cashiers
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to supplies_path, class: "nav-link" do %>
              <span data-feather="package"></span>
              Supply
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to sales_path, class: "nav-link active" do %>
              <span data-feather="shopping-bag"></span>
              Sales
            <% end %>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

app/views/sales/index.html.erb
<% provide(:title, 'Sales') %>

<%= render 'sales/sidebar' %>

<% no = 0 %>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" data-turbo="false">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Sales</h1>
    <%= link_to "New sales", new_sale_path, class: "btn btn-outline-primary" %>
  </div>

  <% if notice %>
    <div class="mx-auto alert alert-success text-center">
      <%= notice %>
    </div>
  <% end %>

  <% unless @sales.empty? %>

  <div class="d-flex flex-wrap align-items-start justify-content-start justify-content-lg-start">
    <table class="table table-stripped table-hover table-align-middle table-primary">
      <thead>
        <tr class="text-center">
          <th scope="col">#</th>
          <th scope="col">Book Title</th>
          <th scope="col">Cashier</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total</th>
          <th scope="col">Date</th>
        </tr>
      </thead>
      <% @sales.each do |sales| %>
        <tbody>
          <tr>
            <th scope="col" class="text-center"><%= no += 1 %></th>
            <td>
              <%= image_tag sales.book.cover, width: "30", class: "img-fluid" if sales.book.cover.attached? %>
              <%= sales.book.title %>
            </td>
            <td class="text-center">
              <%= sales.cashier.name %>
            </td>
            <td class="text-center"><%= sales.quantity %></td>
            <td class="text-center">
              <%= sales.total %>
            </td>
            <td class="text-center"><%= sales.date&.strftime('%d %B %Y') %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>

  <% else %>
    <h1 class="text-center">
      No Data.
    </h1>
  <% end %>
</main>
 
<%= render 'layouts/closing' %>



app/views/sales/new.html.erb
<% provide(:title, 'New Sales') %>

<%= render 'sales/sidebar' %>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
		<h2>New Sales</h2>
	</div>
	<%= render "form", sale: @sale %>
</main>